### ISSUE TITLE
pytorch_fft install

### ISSUE THREAD

**Issue by zhangchen98** [DeepInsight-PCALab/CompactBilinearPooling-Pytorch#13]
when I install pytorch_fft,the problem is：
 error in pytorch_fft setup command: 'C:\\Users\\14375\\AppData\\Local\\Temp\\pip-install-6vh12s8w\\pytorch-fft\\build.py:ffi' must be of the form 'path/build.py:ffi_va
riable'
    Including CUDA code.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Puppetopen** [comment]
yes，I meet the same problem.Do you finish it?

**Comment by Xiaochaosui** [comment]
Hi，I also meet the same problem.Do you finish it?

**Comment by dichen-cd** [comment]
Please refer to [this issue](https://github.com/locuslab/pytorch_fft/issues/43).
