### ISSUE TITLE
No module named _th_fft

### ISSUE THREAD

**Issue by kopingwu** [DeepInsight-PCALab/CompactBilinearPooling-Pytorch#2]
Hi, thanks for your job!
lt looks like there is no module named _th_fft when follow the command as you said.
Do you have any idea about it?
Thanks a lot~
`
dl@dl:~/wxptest$ sudo python wxp.py

Traceback (most recent call last):
  File "wxp.py", line 3, in <module>
    from CompactBilinearPooling import CompactBilinearPooling
  File "/home/dl/wxptest/CompactBilinearPooling.py", line 6, in <module>
    import pytorch_fft.fft.autograd as afft
  File "/home/dl/wxptest/pytorch_fft/__init__.py", line 1, in <module>
    from . import fft
  File "/home/dl/wxptest/pytorch_fft/fft/__init__.py", line 1, in <module>
    from .fft import *
  File "/home/dl/wxptest/pytorch_fft/fft/fft.py", line 3, in <module>
    from .._ext import th_fft
  File "/home/dl/wxptest/pytorch_fft/_ext/th_fft/__init__.py", line 3, in <module>
    from ._th_fft import lib as _lib, ffi as _ffi
ImportError: No module named _th_fft
`

**Comment by dichen-cd** [comment]
Looks like you didn't build pytorch_fft. Would you please try `cd /home/dl/wxptest/pytorch_fft && python setup.py install` and then delete your downloaded file `rm -rf /home/dl/wxptest/pytorch_fft`.

**Comment by xingdi1990** [comment]
Same issue

**Comment by pangjh3** [comment]
same issue. I have try python setup.py install @DeanChan

**Comment by dichen-cd** [comment]
@kopingwu @DetionDX @SkyFlyboy Looks like it's an issue caused by the latest commit of pytorch_fft. [Build issue: No module named _th_fft #26](https://github.com/locuslab/pytorch_fft/issues/26). 

`pip uninstall pytorch_fft` then `pip install pytorch_fft` worked for me. I'll update `README.md` right away.

**Comment by mxtx0509** [comment]
Hello, is your problem solved? Can you train on multiple GPUs? Thanks!
