### ISSUE TITLE
How's the output 

### ISSUE THREAD

**Issue by Paranoidv** [DeepInsight-PCALab/CompactBilinearPooling-Pytorch#4]
Thank you for your job! I have some question, if x = (4,512,64,64), y = (4,512,64,64), a=CompactBilinearPooling(x,y) ， what the shape of a ? And How I can make the a‘s shape is (batch_size,channels,height,width) which the same as x and y？

**Comment by dichen-cd** [comment]
It is determined by `output_dim` when initializing CompactBilinearPooling, thus the shape of `a` should be `(4, output_dim)`. 

Well, I don't quite understand the motivation to align the output shape to that of x and y...
