### ISSUE TITLE
No parameters for optmizer

### ISSUE THREAD

**Issue by bupt-zsp** [DeepInsight-PCALab/CompactBilinearPooling-Pytorch#7]
Thanks for your working, when I apply your code, I meet the situation that  model.parameters() is empty and fail to creat optimizer. Model is compactbilinearpooling(1536,1536,400). Am I wrong? Thanks for answering

**Comment by dichen-cd** [comment]
Compact Bilinear Pooling is by-default non-parametered. No need to optimize this layer.
