### ISSUE TITLE
Possible error in computation

### ISSUE THREAD

**Issue by dormantrepo** [DeepInsight-PCALab/CompactBilinearPooling-Pytorch#9]
According to the existing code beginning here https://github.com/DeepInsight-PCALab/CompactBilinearPooling-Pytorch/blob/56e23d01e687dad067dfeb9a07bb4d012430e1df/CompactBilinearPooling.py#L92 the product of two complex numbers(a+ib, x+iy) is _{(ax-by) + i(ax+by)}_.

       `temp_rr, temp_ii = fft1_real.mul(fft2_real), fft1_imag.mul(fft2_imag)
        fft_product_real = temp_rr - temp_ii
        fft_product_imag = temp_rr + temp_ii

        cbp_flat = afft.Ifft()(fft_product_real, fft_product_imag)[0]`

However the correct product is _{(ax-by) + i(ay+bx)}_ in which case the following product is wrong. 

Correct me if I am wrong.

**Comment by dichen-cd** [comment]
Oh, absolutely, you are right! I was being stupid...
Fixing now.
